version: "3.7"

services:

    weather:
        build: .
        command: python3 /usr/app/weather.py
        volumes:
            - /srv/docker/prefect/flows:/root/.prefect/flows:z
            - ./weather.py:/usr/app/weather.py:z
            - ./config.toml:/root/.prefect/config.toml:z
#              source: ./weather.py
#              target: /usr/app/weather.py
#              read_only: true
#            - type: bind
#              source: ./config.toml
#              target: /root/.prefect/config.toml
#              read_only: true
