version: "3.7"

services:

    agent:
        build: .
        command: bash -c "prefect agent local start --name $$(uuid) --no-hostname-label --label development"
        volumes:
            - /srv/docker/prefect/flows:/root/.prefect/flows:z
            - ./config.toml:/root/.prefect/config.toml:z